# ================================
# Sample sheet for scRNA + Spatial
# ================================

scRNA:
  sample1:
    file: "data_raw/scRNA/sample1.h5ad"
  sample2:
    file: "data_raw/scRNA/sample2.h5ad"

spatial:
  slide1:
    visium_dir: "data_raw/spatial/slide1/"
  slide2:
    visium_dir: "data_raw/spatial/slide2/"
